<?php

namespace Database\Seeders;

use App\Models\Kpi;
use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;

class KpiSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $kpis = [
            // ---------------- UNIV-AC-001: 4-Year Graduation Rate (2024-2025) ----------------
            [
                'measure_code' => 'UNIV-AC-001',
                'measure_owner' => 'Dr. Elizabeth Vance (Provost)',
                'measure_name' => '4-Year Graduation Rate',
                'measure_type' => 'Academic Excellence',
                'category' => 'Academic',
                'year_range' => '2024-2025',
                'description' => 'The percentage of full-time, first-time undergraduate students who complete their baccalaureate degree program within four years.',
                'lead_lag' => 'Lag',
                'polarity' => 'Positive',
                'formula' => '(Number of graduates completing degree in 4 years or less / Total cohort of first-time full-time students 4 years prior) * 100',
                'unit_type' => 'Percentage',
                'data_provider' => 'Office of Institutional Research',
                'data_source' => 'Banner Student ERP System',
                'collection_frequency' => 'Annually',
                'reporting_frequency' => 'Annually',
                'verified_by' => 'Dr. Robert Chen (VP Student Affairs)',
                'validated_by' => 'Academic Senate Committee',
                'baseline' => '58.5%',
                'target' => '62.0%',
                'high_threshold' => '65.0%',
                'low_threshold' => '56.0%',
                'target_rationale' => 'Aligns with our 5-year strategic plan goal to rank in the top tier of regional state universities.',
                'perspective' => 'Student Success & Learning',
                'strategic_theme' => 'Student Centricity & Academic Excellence',
                'objective' => 'Enhance undergraduate completion rates and reduce time-to-degree.',
                'objective_owner' => 'Provost Office',
                'strategic_initiatives' => 'Implement degree mapping tools, launch early-alert advising framework, and expand summer course offerings.',
                'intended_results' => 'Improved student satisfaction, reduced student debt load, and increased national ranking prominence.',
                'comparator' => 'State peer average is 55.4%',
                'item_author' => 'Sarah Jenkins (Institutional Research Analyst)',
                'date' => Carbon::parse('2024-09-15'),
            ],
            // ---------------- UNIV-AC-001: 4-Year Graduation Rate (2025-2026 - Version 2) ----------------
            [
                'measure_code' => 'UNIV-AC-001',
                'measure_owner' => 'Dr. Elizabeth Vance (Provost)',
                'measure_name' => '4-Year Graduation Rate',
                'measure_type' => 'Academic Excellence',
                'category' => 'Academic',
                'year_range' => '2025-2026',
                'description' => 'The percentage of full-time, first-time undergraduate students who complete their baccalaureate degree program within four years.',
                'lead_lag' => 'Lag',
                'polarity' => 'Positive',
                'formula' => '(Number of graduates completing degree in 4 years or less / Total cohort of first-time full-time students 4 years prior) * 100',
                'unit_type' => 'Percentage',
                'data_provider' => 'Office of Institutional Research',
                'data_source' => 'Banner Student ERP System',
                'collection_frequency' => 'Annually',
                'reporting_frequency' => 'Annually',
                'verified_by' => 'Dr. Robert Chen (VP Student Affairs)',
                'validated_by' => 'Academic Senate Committee',
                'baseline' => '60.2%', // Updated baseline based on prior year actuals
                'target' => '64.5%', // Increased target
                'high_threshold' => '67.0%',
                'low_threshold' => '58.0%',
                'target_rationale' => 'Adjusted upwards due to positive impact from the new automated degree audit system.',
                'perspective' => 'Student Success & Learning',
                'strategic_theme' => 'Student Centricity & Academic Excellence',
                'objective' => 'Enhance undergraduate completion rates and reduce time-to-degree.',
                'objective_owner' => 'Provost Office',
                'strategic_initiatives' => 'Implement degree mapping tools, launch early-alert advising framework, and expand summer course offerings.',
                'intended_results' => 'Improved student satisfaction, reduced student debt load, and increased national ranking prominence.',
                'comparator' => 'State peer average is 56.1%',
                'item_author' => 'Sarah Jenkins (Institutional Research Analyst)',
                'date' => Carbon::parse('2025-09-10'),
            ],
            // ---------------- UNIV-RE-002: Research Funding (2024-2025) ----------------
            [
                'measure_code' => 'UNIV-RE-002',
                'measure_owner' => 'Dr. Marcus Thorne (VP of Research)',
                'measure_name' => 'Research Funding Secured ($M)',
                'measure_type' => 'Institutional Growth',
                'category' => 'Research',
                'year_range' => '2024-2025',
                'description' => 'Total annual value of external research grants, contracts, and awards secured by university faculty.',
                'lead_lag' => 'Lag',
                'polarity' => 'Positive',
                'formula' => 'Sum of all external research grants and awards finalized within the fiscal year',
                'unit_type' => 'Millions (USD)',
                'data_provider' => 'Office of Sponsored Programs',
                'data_source' => 'Cayuse Research Suite & General Ledger',
                'collection_frequency' => 'Quarterly',
                'reporting_frequency' => 'Annually',
                'verified_by' => 'Financial Comptroller',
                'validated_by' => 'Board of Trustees Committee on Research',
                'baseline' => '$42.5M',
                'target' => '$45.0M',
                'high_threshold' => '$48.0M',
                'low_threshold' => '$41.0M',
                'target_rationale' => 'Matches the trajectory required to sustain our R2 Carnegie Classification and fund new laboratory infrastructures.',
                'perspective' => 'Financial Stewardship & Growth',
                'strategic_theme' => 'Research Innovation & Discovery',
                'objective' => 'Excellence in research activity and external funding acquisition.',
                'objective_owner' => 'VP of Research Office',
                'strategic_initiatives' => 'Establish new interdisciplinary research seed grants, hire 4 grant writers, and build relations with federal agencies (NSF, NIH).',
                'intended_results' => 'Higher profile research publications, attraction of top-tier doctoral candidates, and capital injections for core facilities.',
                'comparator' => 'Peer average is $41.8M',
                'item_author' => 'Michael Henderson (Director of OSP)',
                'date' => Carbon::parse('2024-07-01'),
            ],
            // ---------------- UNIV-RE-002: Research Funding (2025-2026 - Version 2) ----------------
            [
                'measure_code' => 'UNIV-RE-002',
                'measure_owner' => 'Dr. Marcus Thorne (VP of Research)',
                'measure_name' => 'Research Funding Secured ($M)',
                'measure_type' => 'Institutional Growth',
                'category' => 'Research',
                'year_range' => '2025-2026',
                'description' => 'Total annual value of external research grants, contracts, and awards secured by university faculty.',
                'lead_lag' => 'Lag',
                'polarity' => 'Positive',
                'formula' => 'Sum of all external research grants and awards finalized within the fiscal year',
                'unit_type' => 'Millions (USD)',
                'data_provider' => 'Office of Sponsored Programs',
                'data_source' => 'Cayuse Research Suite & General Ledger',
                'collection_frequency' => 'Quarterly',
                'reporting_frequency' => 'Annually',
                'verified_by' => 'Financial Comptroller',
                'validated_by' => 'Board of Trustees Committee on Research',
                'baseline' => '$46.2M', // Reflects growth from previous year
                'target' => '$50.0M', // Adjusted higher for new era
                'high_threshold' => '$53.0M',
                'low_threshold' => '$45.0M',
                'target_rationale' => 'Aiming for a stretch goal to accelerate transition to R1 classification over the next decade.',
                'perspective' => 'Financial Stewardship & Growth',
                'strategic_theme' => 'Research Innovation & Discovery',
                'objective' => 'Excellence in research activity and external funding acquisition.',
                'objective_owner' => 'VP of Research Office',
                'strategic_initiatives' => 'Launch the National Security Innovation Institute, create joint venture programs with local tech industries, and optimize overhead return formulas.',
                'intended_results' => 'Higher profile research publications, attraction of top-tier doctoral candidates, and capital injections for core facilities.',
                'comparator' => 'Peer average is $43.2M',
                'item_author' => 'Michael Henderson (Director of OSP)',
                'date' => Carbon::parse('2025-06-30'),
            ],
            // ---------------- UNIV-FI-003: Endowment Growth Rate (2025-2026) ----------------
            [
                'measure_code' => 'UNIV-FI-003',
                'measure_owner' => 'Julian Sterling (Chief Investment Officer)',
                'measure_name' => 'Endowment Growth Rate',
                'measure_type' => 'Financial Health',
                'category' => 'Financial',
                'year_range' => '2025-2026',
                'description' => 'Annual percentage growth of the university’s investment endowment portfolio after distribution payout.',
                'lead_lag' => 'Lag',
                'polarity' => 'Positive',
                'formula' => '((Endowment Value End of Year - Endowment Value Start of Year + Distributions) / Endowment Value Start of Year) * 100',
                'unit_type' => 'Percentage',
                'data_provider' => 'University Foundation Finance Team',
                'data_source' => 'Merrill Lynch Investment Portals & General Ledger',
                'collection_frequency' => 'Quarterly',
                'reporting_frequency' => 'Annually',
                'verified_by' => 'PwC External Auditors',
                'validated_by' => 'Foundation Investment Board',
                'baseline' => '6.4%',
                'target' => '8.0%',
                'high_threshold' => '10.0%',
                'low_threshold' => '4.0%',
                'target_rationale' => 'Required to maintain purchasing power inflation-adjusted, and support the 4.5% annual payout rate for student scholarships.',
                'perspective' => 'Financial Stewardship & Growth',
                'strategic_theme' => 'Sustainable Resources & Growth',
                'objective' => 'Preserve and grow the university’s long-term financial resources.',
                'objective_owner' => 'University Foundation CIO',
                'strategic_initiatives' => 'Reallocate assets to private equity, initiate a $250M capital campaign for scholarships, and negotiate reduced management fees.',
                'intended_results' => 'Increased volume of endowed student scholarships and long-term institutional self-sufficiency.',
                'comparator' => 'NACUBO National Endowment Study average is 7.2%',
                'item_author' => 'Elena Rostova (Foundation Portfolio Manager)',
                'date' => Carbon::parse('2025-08-01'),
            ],
            // ---------------- UNIV-ST-004: First-Year Retention Rate (2024-2025) ----------------
            [
                'measure_code' => 'UNIV-ST-004',
                'measure_owner' => 'Dr. Robert Chen (VP Student Affairs)',
                'measure_name' => 'First-Year Retention Rate',
                'measure_type' => 'Student Success',
                'category' => 'Student Services',
                'year_range' => '2024-2025',
                'description' => 'The percentage of first-time, full-time freshman students who enroll in the subsequent fall semester.',
                'lead_lag' => 'Lag',
                'polarity' => 'Positive',
                'formula' => '(Freshman cohort enrolled in Fall Year N+1 / Total freshman cohort enrolled in Fall Year N) * 100',
                'unit_type' => 'Percentage',
                'data_provider' => 'Office of Enrollment Management',
                'data_source' => 'Banner ERP Census Files',
                'collection_frequency' => 'Annually',
                'reporting_frequency' => 'Annually',
                'verified_by' => 'Dr. Elizabeth Vance (Provost)',
                'validated_by' => 'Enrollment Management Council',
                'baseline' => '78.2%',
                'target' => '82.0%',
                'high_threshold' => '84.0%',
                'low_threshold' => '76.0%',
                'target_rationale' => 'Improving retention is the primary driver for our long-term enrollment and fiscal stability strategy.',
                'perspective' => 'Student Success & Learning',
                'strategic_theme' => 'Student Centricity & Academic Excellence',
                'objective' => 'Optimize student support and onboarding to foster successful transition to college.',
                'objective_owner' => 'Student Affairs Division',
                'strategic_initiatives' => 'Establish First-Year Experience (FYE) seminars, peer mentoring program in dormitories, and standardizing free peer tutoring.',
                'intended_results' => 'Higher degree progression rates, better student engagement indicators, and stronger institutional affinity.',
                'comparator' => 'Peer average is 79.5%',
                'item_author' => 'Liam O\'Connor (Retention Coordinator)',
                'date' => Carbon::parse('2024-10-15'),
            ],
            // ---------------- UNIV-ST-004: First-Year Retention Rate (2025-2026 - Version 2) ----------------
            [
                'measure_code' => 'UNIV-ST-004',
                'measure_owner' => 'Dr. Robert Chen (VP Student Affairs)',
                'measure_name' => 'First-Year Retention Rate',
                'measure_type' => 'Student Success',
                'category' => 'Student Services',
                'year_range' => '2025-2026',
                'description' => 'The percentage of first-time, full-time freshman students who enroll in the subsequent fall semester.',
                'lead_lag' => 'Lag',
                'polarity' => 'Positive',
                'formula' => '(Freshman cohort enrolled in Fall Year N+1 / Total freshman cohort enrolled in Fall Year N) * 100',
                'unit_type' => 'Percentage',
                'data_provider' => 'Office of Enrollment Management',
                'data_source' => 'Banner ERP Census Files',
                'collection_frequency' => 'Annually',
                'reporting_frequency' => 'Annually',
                'verified_by' => 'Dr. Elizabeth Vance (Provost)',
                'validated_by' => 'Enrollment Management Council',
                'baseline' => '80.5%', // Improvement shown from FYE initiative
                'target' => '84.0%',
                'high_threshold' => '86.0%',
                'low_threshold' => '78.0%',
                'target_rationale' => 'Capitalizing on the successful pilot of the peer-mentoring program which showed a 3.5% retention spike.',
                'perspective' => 'Student Success & Learning',
                'strategic_theme' => 'Student Centricity & Academic Excellence',
                'objective' => 'Optimize student support and onboarding to foster successful transition to college.',
                'objective_owner' => 'Student Affairs Division',
                'strategic_initiatives' => 'Scale peer mentoring program, launch predictive-analytics-driven advising dashboard, and expand emergency student grants.',
                'intended_results' => 'Higher degree progression rates, better student engagement indicators, and stronger institutional affinity.',
                'comparator' => 'Peer average is 80.1%',
                'item_author' => 'Liam O\'Connor (Retention Coordinator)',
                'date' => Carbon::parse('2025-10-10'),
            ],
            // ---------------- UNIV-AD-005: Greenhouse Gas Emissions Reduction (2025-2026) ----------------
            [
                'measure_code' => 'UNIV-AD-005',
                'measure_owner' => 'Marcus Vance (AVP Facilities Management)',
                'measure_name' => 'Greenhouse Gas Emissions Reduction',
                'measure_type' => 'Sustainability',
                'category' => 'Administration',
                'year_range' => '2025-2026',
                'description' => 'Percentage reduction in Scope 1 and Scope 2 CO2-equivalent emissions compared to the 2020 campus baseline.',
                'lead_lag' => 'Lag',
                'polarity' => 'Positive', // Higher percentage reduction is positive
                'formula' => '((Total Metric Tons CO2e in 2020 - Total Metric Tons CO2e in Current Year) / Total Metric Tons CO2e in 2020) * 100',
                'unit_type' => 'Percentage',
                'data_provider' => 'Office of Sustainability',
                'data_source' => 'Utility Bills, Fleet Fuel Logs, and Energy Cap Software',
                'collection_frequency' => 'Monthly',
                'reporting_frequency' => 'Annually',
                'verified_by' => 'Greener Schools Coalition',
                'validated_by' => 'Campus Sustainability Advisory Council',
                'baseline' => '12.0%',
                'target' => '25.0%',
                'high_threshold' => '30.0%',
                'low_threshold' => '20.0%',
                'target_rationale' => 'Paves the way to achieve carbon neutrality by 2035 in accordance with the President’s Climate Commitment.',
                'perspective' => 'Operational Excellence & Infrastructure',
                'strategic_theme' => 'Sustainability & Infrastructure Modernization',
                'objective' => 'Improve carbon footprint and operational sustainability.',
                'objective_owner' => 'AVP Facilities Office',
                'strategic_initiatives' => 'Upgrade HVAC systems to high-efficiency models, convert 40% of fleet vehicles to EV, and install 1.2MW solar arrays on campus roofs.',
                'intended_results' => 'Reduced campus energy costs, improved sustainability ratings (AASHE STARS Gold), and real-world climate education opportunities.',
                'comparator' => 'State university average reduction is 18%',
                'item_author' => 'Dr. Clara Higgins (Director of Sustainability)',
                'date' => Carbon::parse('2025-07-15'),
            ],
            // ---------------- UNIV-HR-006: Professional Development Engagement (2025-2026) ----------------
            [
                'measure_code' => 'UNIV-HR-006',
                'measure_owner' => 'Sophia Delgado (VP of Human Resources)',
                'measure_name' => 'Faculty & Staff Professional Development Hours',
                'measure_type' => 'Employee Development',
                'category' => 'Administration',
                'year_range' => '2025-2026',
                'description' => 'The average number of documented professional development, training, or workshop hours completed per full-time employee annually.',
                'lead_lag' => 'Lead', // This is a Lead indicator for employee performance and satisfaction
                'polarity' => 'Positive',
                'formula' => 'Total training hours logged in Workday Learning / Total full-time equivalent (FTE) employees',
                'unit_type' => 'Hours',
                'data_provider' => 'Human Resources Training Unit',
                'data_source' => 'Workday ERP Learning Management System',
                'collection_frequency' => 'Monthly',
                'reporting_frequency' => 'Quarterly',
                'verified_by' => 'HR Director of Operations',
                'validated_by' => 'Staff Council Representatives',
                'baseline' => '12.4 hours',
                'target' => '20.0 hours',
                'high_threshold' => '24.0 hours',
                'low_threshold' => '15.0 hours',
                'target_rationale' => 'Upskilling is essential to support digital transformation initiatives and improve campus culture metrics.',
                'perspective' => 'Organizational Readiness & Learning',
                'strategic_theme' => 'Employer of Choice & Staff Empowerment',
                'objective' => 'Cultivate a culture of continuous learning and growth.',
                'objective_owner' => 'Human Resources Division',
                'strategic_initiatives' => 'Launch the Leadership Development Academy, subsidize Coursera certifications, and dedicate 2 hours of paid training per week.',
                'intended_results' => 'Lower employee turnover, higher internal promotion rates, and smoother adoption of enterprise tools.',
                'comparator' => 'Higher-ed HR benchmark is 18 hours',
                'item_author' => 'Arthur Pendelton (Learning Coordinator)',
                'date' => Carbon::parse('2025-06-01'),
            ]
        ];

        foreach ($kpis as $kpiData) {
            Kpi::create($kpiData);
        }
    }
}
